# Generated by Django 5.2.6 on 2026-02-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='z_index',
            field=models.IntegerField(default=0),
        ),
    ]
