# Generated by Django 5.2.6 on 2026-02-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_numbertest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.DeleteModel(
            name='NumberTest',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(),
        ),
    ]
