# Generated by Django 5.2.6 on 2026-02-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_milestone_project_dependency_task_milestone_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='scheduled_index',
            new_name='end_index',
        ),
        migrations.AddField(
            model_name='milestone',
            name='start_index',
            field=models.IntegerField(default=0),
        ),
    ]
