# Generated by Django 5.2.6 on 2026-02-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
