# Generated by Django 5.2.6 on 2026-02-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_scheduled_index_milestone_end_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
            preserve_default=False,
        ),
    ]
