# Generated by Django 6.0.2 on 2026-02-14 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_milestone_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='end_index',
        ),
        migrations.AddField(
            model_name='milestone',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='api.task'),
        ),
    ]
