# Generated by Django 5.2.6 on 2026-02-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
