# Generated by Django 5.2.6 on 2026-02-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_legendtype_idea_legend_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
