# Generated by Django 5.2.6 on 2026-02-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_idea_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='idea',
            name='order_number',
        ),
    ]
