# Generated by Django 5.2.6 on 2026-02-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ideaorder_remove_idea_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
