# Generated by Django 5.2.6 on 2026-02-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_idea_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
